# Site settings
title: Windsoldier76's Data Structure Learning Path
email:
description: > # this means to ignore newlines until "baseurl:"
  Windsoldier76 is an Overwatch fan
baseurl: "/data_structure" # the subpath of your site, e.g. /blog/
url: "https://windsoldier76.github.io/data_structure/" # the base hostname & protocol for your site
twitter_username: username
github_username: Windsoldier76

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
future: true

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
